print("-------------")
print("python has entered the building")
print("let the party start!")
print("-------------")
print("This is a sample Python script.")
print("It demonstrates basic print functionality.")
print("You can run this script using a Python interpreter.")
print("-------------")
print("End of the sample script.")
print("-------------")
print("Thank you for using Python!")
